name:                MathGame
version:             0.1.0.0
github:              "githubuser/MathGame"
license:             BSD3
author:              "Miguel"
maintainer:          "tralafarlaw@gmail.com"
copyright:           "2021 Miguel Murillo Bernal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/MathGame#readme>

dependencies:
- base >= 4.7 && < 5
- text
# - haskell-say >= 1.0.0.0
- gloss
- QuickCheck >= 2.14.2
- OpenGL
- GLUT
- random
- gloss-juicy >= 0.2.3
library:
  source-dirs: src

executables:
  MathGame-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MathGame

tests:
  MathGame-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MathGame
